services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: murkkot/jenkins-docker:latest
    container_name: jenkins
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - '999'
    restart: unless-stopped