---
- name: Add samba share
  hosts: homeserver
  become: true

  vars:
    share_name: various
    share_path: /mnt/hdd/various
    share_block: |
      [{{ share_name }}]
      comment = Various
      path = {{ share_path }}
      writable = yes
      browsable = yes
      create mask = 0775

  tasks:
    - name: "Add share to smb.conf"
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {mark} ANSIBLE {{ share_name | upper }} SHARE"
        block: "{{ share_block }}"
        insertafter: EOF
        backup: yes
      notify: Restart smbd

  handlers:
    - name: Restart smbd
      ansible.builtin.service:
        name: smbd
        state: restarted